parserOptions:
    ecmaVersion: latest
    sourceType: module
env:
    es6: true
    jasmine: true
    node: true
extends: eslint:recommended
rules:
    accessor-pairs: error
    array-bracket-spacing:
        - error
        - never
    array-callback-return: error
    block-spacing:
        - error
        - never
    brace-style: error
    comma-dangle: error
    comma-spacing: error
    comma-style: error
    complexity:
        - error
        - 10
    computed-property-spacing: error
    consistent-return: error
    consistent-this: error
    constructor-super: error
    curly: error
    default-case: error
    dot-notation: error
    eol-last: error
    eqeqeq: error
    generator-star-spacing: error
    global-require: off
    guard-for-in: error
    jsx-quotes: error
    key-spacing: error
    keyword-spacing: error
    linebreak-style: error
    lines-around-comment:
        - error
        -
            allowBlockStart: true
            allowObjectStart: true
            allowArrayStart: true
    max-statements-per-line: error
    new-cap: error
    new-parens: error
    no-array-constructor: error
    no-bitwise: error
    no-caller: error
    no-case-declarations: error
    no-catch-shadow: error
    no-class-assign: error
    no-cond-assign: error
    no-confusing-arrow: error
    no-console: off
    no-const-assign: error
    no-constant-condition: error
    no-continue: error
    no-delete-var: error
    no-dupe-args: error
    no-dupe-class-members: error
    no-dupe-keys: error
    no-duplicate-case: error
    no-duplicate-imports: error
    no-empty: off
    no-empty-character-class: error
    no-empty-pattern: error
    no-eq-null: error
    no-eval: error
    no-extend-native: error
    no-extra-bind: error
    no-extra-boolean-cast: error
    no-extra-label: error
    no-extra-semi: error
    no-fallthrough: error
    no-func-assign: error
    no-implied-eval: error
    no-inner-declarations: error
    no-invalid-this: error
    no-invalid-regexp: error
    no-irregular-whitespace: error
    no-iterator: error
    no-label-var: error
    no-labels: error
    no-lone-blocks: error
    no-lonely-if: error
    no-loop-func: error
    no-mixed-spaces-and-tabs: error
    no-multi-spaces: error
    no-multi-str: error
    no-multiple-empty-lines:
        - error
        -
            max: 2
    no-native-reassign: error
    no-negated-condition: error
    no-nested-ternary: error
    no-new: error
    no-new-func: error
    no-new-object: error
    no-new-symbol: error
    no-new-wrappers: error
    no-obj-calls: error
    no-octal: error
    no-octal-escape: error
    no-path-concat: error
    no-plusplus: error
    no-proto: error
    no-redeclare: error
    no-regex-spaces: error
    no-restricted-globals: error
    no-return-assign: error
    no-script-url: error
    no-self-assign: error
    no-self-compare: error
    no-sequences: error
    no-shadow: error
    no-shadow-restricted-names: error
    no-spaced-func: error
    no-sparse-arrays: error
    no-this-before-super: error
    no-throw-literal: error
    no-trailing-spaces: error
    no-undef: error
    no-undef-init: error
    no-unexpected-multiline: error
    no-unmodified-loop-condition: error
    no-unneeded-ternary: error
    no-unreachable: error
    no-unsafe-finally: error
    no-unused-expressions: error
    no-unused-labels: error
    no-unused-vars: error
    no-useless-call: error
    no-useless-computed-key: error
    no-useless-concat: error
    no-useless-constructor: error
    no-useless-escape: error
    no-void: error
    no-warning-comments: warn
    no-whitespace-before-property: error
    no-with: error
    operator-assignment: error
    padded-blocks:
        - error
        - never
    prefer-const: error
    quote-props:
        - error
        - as-needed
    radix: error
    require-yield: error
    semi: error
    semi-spacing: error
    space-before-blocks: error
    space-in-parens: error
    space-infix-ops:
        - error
        -
            int32Hint: false
    space-unary-ops: error
    spaced-comment: error
    use-isnan: error
    valid-typeof: error
    yield-star-spacing: error
