#!/usr/bin/env bash

cd "$(dirname "$0")" || exit 1

# shellcheck disable=SC1091
. ./mo
PASS=0
FAIL=0

source ./run-basic-tests

echo ""
echo "Pass: $PASS"
echo "Fail: $FAIL"
if [[ $FAIL -gt 0 ]]; then
    exit 1
fi
