#!/usr/bin/env bash

# Install or update the specs
if [[ ! -d spec ]]; then
    git clone https://github.com/mustache/spec.git spec
else
    (
        cd spec
        git pull
    )
fi

if [[ "$BASH_VERSION" == 3.* ]]; then
    echo "WARNING! Specs assume you are using a version of Bash with associative arrays!"
fi

# Actually run the specs
node run-spec.js spec/specs/*.json

if [[ "$BASH_VERSION" == 3.* ]]; then
    echo "Some tests may have failed because they assume Bash supports associative arays"
fi
