#!/usr/bin/env bash

# Install or update the specs
if [[ ! -d spec ]]; then
    git clone https://github.com/mustache/spec.git spec
else
    (
        cd spec
        git pull
    )
fi

# Actually run the specs
node run-spec.js spec/specs/*.json

