#!/usr/bin/env bash
cd "${0%/*}" || exit 1
. ../run-tests

declare -A repo
# The order of the array elements can be shuffled depending on the version of
# Bash. Keeping this to a minimal set and alphabetized seems to help.
repo[hub]="Hub"
repo[rip]="Rip"
export repo
template() {
    cat <<EOF
{{#repo}}
  <b>{{@key}} - {{.}}</b>
{{/repo}}
EOF
}
expected() {
    cat <<EOF
  <b>hub - Hub</b>
  <b>rip - Rip</b>
EOF
}

runTest
