#!/usr/bin/env bash
cd "${0%/*}" || exit 1
. ../run-tests

template() {
    cat <<EOF
<h1>Today{{! ignore me
and this can
run through multiple
lines}}.</h1>
EOF
}
export expected=$'<h1>Today.</h1>\n'

runTest
