#!/usr/bin/env bash
cd "${0%/*}" || exit 1
. ../run-tests

export USER=j.doe
export ADMIN=false
MO_FALSE_IS_EMPTY=yeppers
template() {
    cat <<EOF
The user {{USER}} exists.
{{#ADMIN}}
WRONG - should not be an admin.
{{/ADMIN}}
EOF
}
export expected=$'The user j.doe exists.\n'

runTest
