#!/usr/bin/env bash
cd "${0%/*}" || exit 1
. ../run-tests

export name=Willy
wrapped() {
    # Wrapping 'cat' in a subshell eats the trailing whitespace
    # The echo adds a newline, which is preserved.
    echo "<b>$(cat)</b>"
}
template() {
    cat <<EOF
{{#wrapped}}
  {{name}} is awesome.
{{/wrapped}}
... this is the last line.
EOF
}
export expected=$'<b>  Willy is awesome.</b>\n... this is the last line.\n'

runTest
