#!/usr/bin/env bash
cd "${0%/*}" || exit 1
. ../run-tests

template=""
arguments=(--help)
expected() {
    cat <<EOF
Mo is a mustache template rendering software written in bash.  It inserts
environment variables into templates.

Simply put, mo will change {{VARIABLE}} into the value of that
environment variable.  You can use {{#VARIABLE}}content{{/VARIABLE}} to
conditionally display content or iterate over the values of an array.

Learn more about mustache templates at https://mustache.github.io/

Simple usage:

   mo [OPTIONS] filenames...

Options:

   -u, --fail-not-set
         Fail upon expansion of an unset variable.
   -x, --fail-on-function
         Fail when a function returns a non-zero status code.
   -e, --false
         Treat the string "false" as empty for conditionals.
   -h, --help
         This message.
   -s=FILE, --source=FILE
         Load FILE into the environment before processing templates.
         Can be used multiple times.

MO_VERSION=3.0.0
EOF
}

runTest
