#!/usr/bin/env bash
cd "${0%/*}" || exit 1
. ../run-tests

export person=""
export template=""
export returnCode=1
export arguments=(--something)
export expected=$'ERROR: Unknown option: --something (See --help for options)\n'

runTest
