#!/usr/bin/env bash
cd "${0%/*}" || exit 1
. ../run-tests

export USER=jwerle
export GENDER=male
export THING=apple
export COLOR=red
export PERSON=tobi
export ADJECTIVE=cool
template() {
    cat <<EOF
{{! this is a comment }}

{{USER}} is {{GENDER}}
{{THING}} is {{COLOR}}
{{PERSON}} is {{ADJECTIVE}}
{{USER}} is friends with {{PERSON}}
{{var}} {{value}}
EOF
}
expected() {
    cat <<EOF

jwerle is male
apple is red
tobi is cool
jwerle is friends with tobi
 
EOF
}

runTest
