#!/usr/bin/env bash
cd "${0%/*}" || exit 1
. ../run-tests

export names=( "Tyler" "Abc" )
template() {
    cat <<EOF
<h2>Names</h2>
{{#names}}
  {{> fixtures/partial.partial}}
{{/names}}
EOF
}
expected() {
    cat <<EOF
<h2>Names</h2>
  <strong>Tyler</strong>
  <strong>Abc</strong>
EOF
}

runTest
