#!/usr/bin/env bash
cd "${0%/*}" || exit 1
. ../run-tests

export NAME="Chris"
export VALUE=10000
export TAXED_VALUE=6000
export IN_CA=true
template() {
    cat <<EOF
Hello {{NAME}}
You have just won {{VALUE}} dollars!
{{#IN_CA}}
Well, {{TAXED_VALUE}} dollars, after taxes.
{{/IN_CA}}
EOF
}
expected() {
    cat <<EOF
Hello Chris
You have just won 10000 dollars!
Well, 6000 dollars, after taxes.
EOF
}

runTest
