#!/usr/bin/env bash
#
# This shows the key and value of an array element being appended
# to a function call's arguments list

cd "$(dirname "$0")" # Go to the script's directory

declare -A DATA
DATA=([one]=111 [two]=222)
. ../mo

declare -a OTHER_DATA
OTHER_DATA=(foo bar)

LIST_ITEM() {
    echo "- $1: $2"
}

SPECIAL_LIST_ITEM() {
    echo "- [$1](./?item=$2): $3"
}

cat <<EOF | mo --allow-function-arguments
Accessing data directly:
    DATA: {{DATA}}
    One: {{DATA.one}}
    Two: {{DATA.two}}

Things in DATA:
{{#DATA}}
    {{LIST_ITEM}}
    {{SPECIAL_LIST_ITEM Click}}
{{/DATA}}
EOF
