#!/usr/bin/env bash
cd "$(dirname "$0")" # Go to the script's directory
export ARRAY=( one two "three three three" four five )
. ../mo
cat << EOF | mo
Here are the items in the array:
{{#ARRAY}}
    * {{.}}
{{/ARRAY}}
EOF
